/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import type { NextPage } from 'next';
import Header from '../components/Header';
import Hero from '../components/Hero';
import About from '../components/About';

const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>Ganzo's portfolio</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      {/* HEADER */}
      <Header />
      {/* HERO */}
      <section id='hero' className='snap-start'>
        <Hero />
      </section>
      {/* ABOUT */}
      <section id='about' className='snap-center'>
        <About />
      </section>
      {/* Experience */}
      {/* Skils */}
      {/* Projects */}
      {/* Contact me */}
    </div>
  );
};

export default Home;

//snap-center ==> scroll-snap-align:center
