import Head from 'next/head';
import type { NextPage } from 'next';
import Header from '../components/Header';
import Hero from '../components/Hero';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ganzo's portfolio</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      {/* HEADER */}
      <Header />
      {/* HERO */}
      <section id='hero'>
        <Hero />
      </section>
      {/* ABOUT */}
      {/* Experience */}
      {/* Skils */}
      {/* Projects */}
      {/* Contact me */}
    </div>
  );
};

export default Home;
